name: CI

on:
  repository_dispatch:
    types: on-demand-test
  push:

jobs:
  push-job:
    name: Somebody pushed me
    runs-on: ubuntu-latest
    steps:
      - name: Yell
        run: |
          echo "I was pushed"

      - name: Get current branch Git commit
        id: consumer_version
        run: echo "app_version=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Check stuff
        if: ${{ success() }}
        run: SAMPLE_VAR='test' npm run test -- --randomVar=${APP_VERSION}
